version: "3.11"
services:
  answer:
    image: answer
    build: ./answer/
    ports:
      - "8082:8082"
    depends_on:
      postgres-db:
        condition: service_started
      goose:
        condition: service_completed_successfully
    environment:
      DATA_SOURCE_NAME: host=postgres-db user=postgres password=postgres dbname=postgres port=5432 sslmode=disable TimeZone=UTC
  postgres-db:
    container_name: postgres-db
    image: postgres:latest
    restart: always
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 1s
      timeout: 1s
      retries: 5
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "postgres"
    volumes:
      - db-data:/var/lib/postgresql
  goose:
    container_name: goose
    image: gomicro/goose:latest
    depends_on:
      postgres-db:
        condition: service_healthy
    volumes:
      - ./answer/migrations:/migrations
    command: ["goose", "-dir", "/migrations", "postgres", "postgresql://postgres:postgres@postgres-db:5432/postgres", "up"]
volumes:
  db-data:
    driver: local